apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: petclicnic-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1  # Ensure this is correct
    kind: Deployment
    name: petclinic-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

